### ISSUE TITLE
Beautiful PropEr - property based testing

### ISSUE THREAD

**Issue by drozzy** [ElixirOttawaMeetup/MeetUpIdeas#12]
Another beautiful tutorial by Fred Hebert:
http://propertesting.com/book_foundations_of_property_based_testing.html

Would make for a nice talk.

**Comment by maxneuvians** [comment]
Looks like a good topic - if you would like to present @drozzy that would be awesome. You can either do something small 5-15 mins or something longer 30-60.

**Comment by drozzy** [comment]
@maxneuvians I've not touched that in a while. Also, it's in erlang, are people ok with that?

I could convert it to Elixir, I suppose.

**Comment by maxneuvians** [comment]
Yes - I think exposing too much Erlang would probably be confusing to a lot of the people just starting Elixir. As you have probably seen it would be pretty easy to call erlang functions from Elixir with the `:module.function` syntax. I also saw this recently: https://github.com/parroty/excheck. Property testing as a concept would be highly interesting though for everybody regardless of language.

**Comment by drozzy** [comment]
This is a bit of a conundrum.
Because it uses erlang macros - I don't really know how to _convert_ it to Elixir.

I only worked with PropEr myself, and yes, concepts are pretty much language independent.

I can probably pull it off in excheck as well (just looked at it, looks similar).
But I'm thinking if maybe PropEr will actually be more interesting (as it is pretty famous).

Btw, when do you want it?

**Comment by maxneuvians** [comment]
Up to you! You can either do it next Monday or in September.

**Comment by drozzy** [comment]
You mean July 24? Sure, since you already have a presentation going, I'll do only 15 minutes or so.

**Comment by maxneuvians** [comment]
I can move that - that one really was only a filler because nobody wanted to present. You can do much longer if you like, I think people will have a good amount of questions as well because it is a new concept.

**Comment by maxneuvians** [comment]
However, if the timeframe to plan something longer is too short, we can also do it another time.

**Comment by drozzy** [comment]
I can do shorter or longer, don't matter to me.

**Comment by maxneuvians** [comment]
ok plan to do like 30-45 mins and then I think we will have some good amount of questions

**Comment by drozzy** [comment]
Ok.

**Comment by drozzy** [comment]
I only got MacBook with a USB-C connection. Will that work?

**Comment by maxneuvians** [comment]
Yes - the meetup is now at survey monkey and they are pretty well equipped!
