### ISSUE TITLE
Any interest in event sourcing?

### ISSUE THREAD

**Issue by drozzy** [ElixirOttawaMeetup/MeetUpIdeas#13]
Could show the use of Elixir's Extreme library, which integrates with EventStore (https://geteventstore.com):
https://github.com/exponentially/extreme

But this is a bit of a narrow field of interest topic. In fact, I'm waiting for a place to host a DDD/CQRS meetup (might not find it) - but in the meantime I could talk about some topics here.

**Comment by maxneuvians** [comment]
This is pretty awesome - we have talked about CQRS in the past at the meetup and it would be great to have a talk on it, all you need to tell me is when you would like to do it.

**Comment by drozzy** [comment]
I can do it anytime after Aug 17th 2017 or so.

I can talk either about EventSourcing or CQRS. Talking about both at once would take too much time.
The CQRS is the drier of the two. EventSourcing is less practical on it's own, but (imo) more interesting.

I am happy to do either, depending on what people want to know more about.
For those interested, there is an excellent slack group:
https://ddd-cqrs-es.herokuapp.com/

**Comment by uri** [comment]
I'm also very interested in event sourcing and CQRS you mentioned the popular [EventStore](https://github.com/slashdotdash/eventstore) lib but there's also [Commanded](https://github.com/slashdotdash/commanded).

Here's a great article on the topic if you want some ideas of how it's framed in Elixir https://10consulting.com/2017/01/04/building-a-cqrs-web-application-in-elixir-using-phoenix/

**Comment by drozzy** [comment]
Commanded sure solves a lot of problems. I've looked at it briefly but decided to defer learning it until it is a bit more mature (as it does, essentially, make you buy into another framework).

It looks good after you program the command handlers yourself and then have to do the clunky serialization/deserialization and pushing events to event store on every node of your system. So I might use it in the future.

**Comment by drozzy** [comment]
Tried commanded. Works brilliantly (for aggregate roots, at least - haven't tried to implement pm or projections yet).

**Comment by maxneuvians** [comment]
Hi @drozzy, Would you like to present this at the Meetup on the 25th of September?

**Comment by drozzy** [comment]
Sure.

**Comment by maxneuvians** [comment]
Awesome! Thank you @drozzy

**Comment by maxneuvians** [comment]
Scheduled for Sept. 25th

**Comment by drozzy** [comment]
Ok!
