### ISSUE TITLE
Demo of Flow with real life example

### ISSUE THREAD

**Issue by maxneuvians** [ElixirOttawaMeetup/MeetUpIdeas#5]
It would be great if somebody could do a presentation on `Flow` https://hexdocs.pm/flow/Flow.html with a real life example and some lessons learned.

**Comment by uri** [comment]
I'm interested in presenting this! Would love some suggestions on a real world use case.

**Comment by maxneuvians** [comment]
Awesome, would you be able to present at the next meetup? I can come up with some suggestions later today.

**Comment by uri** [comment]
Yeah I can do the next meetup.

**Comment by maxneuvians** [comment]
Scheduled for April 17th, 2017

**Comment by maxneuvians** [comment]
Ok couple of ideas:

- Explain the word counter example from the documentation 
- Interesting is also the infinite stream, so some map-reduce job that collect arbitrary data points (page view, ad clicks, heatmap, bidding on an auction item, polling for an action in a collective play video game, current listeners to a stream/socket)
- Friends in common in a social network

**Comment by uri** [comment]
> Explain the word counter example from the documentation

This is what I was originally going to do, but then you prefaced it with "real world example" haha.

**Comment by nicbet** [comment]
also accepting PRs into nicbet/essence with faster word count code ;-)

**Comment by maxneuvians** [comment]
Scheduled for April 24th, 2017 because of Easter 🐰
