### ISSUE TITLE
Accepting Payments through Stripe, Elixir and Phoenix

### ISSUE THREAD

**Issue by aforward** [ElixirOttawaMeetup/MeetUpIdeas#7]
A barebones umbrella application with a "Pay Now" form for collecting $$ through Stripe.

<img width="601" alt="screen shot 2017-03-21 at 3 52 12 pm" src="https://cloud.githubusercontent.com/assets/48086/24167773/6027aae2-0e4e-11e7-896c-ff841ae20be2.png">

Note that the Stripe libraries are currently in flux, so we will be accessing the API "directly" through HTTPoision.  Here you will see Ecto in action (saving the callbacks and notifcations), calling web services, and splitting up your app between many small apps within an umbrella application.

**Comment by maxneuvians** [comment]
Scheduled for April 17th, 2017

**Comment by nicbet** [comment]
So excited for this talk!

**Comment by maxneuvians** [comment]
Scheduled for April 24th, 2017 because of Easter 🐰

**Comment by maxneuvians** [comment]
Scheduled for June 26th!
